# Generated by Django 2.0.1 on 2018-03-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='college',
        ),
    ]
