# Generated by Django 2.0.1 on 2018-03-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_politician_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='area',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politician',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
