# Generated by Django 2.0.1 on 2018-03-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180307_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
