# Generated by Django 2.0.1 on 2018-03-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180307_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='present',
        ),
    ]
