# Generated by Django 2.0.1 on 2018-03-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_politician_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='dateUpdate',
            field=models.DateField(null=True),
        ),
    ]
