# Generated by Django 2.0.1 on 2018-03-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180307_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='placeOfBirth',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
